### PR TITLE
Add section  team/contributors 

### PR DESCRIPTION
**Pull request by GMalacaria**
Added team/collaborators section on the About page:

- Ermanno Battista
- Luciano Murruni
- Marco Matascioli
- Raul Valentini
- Giuseppe Ettorre (missing photo)
- Valentina Ricci
- Claudia Biondi

eg: https://tailwindflex.com/@sienna/meet-the-team-section

### CODE REVIEW

**Comment by lucianomurr** [comment]
@GMalacaria add also Giovanni Malacaria! :)

**Comment by GMalacaria** [comment]
@peppoasap  Can you directly provide me with a URL to the image? to be inserted as src

**Comment by peppoasap** [comment]
> @peppoasap Can you directly provide me with a URL to the image? to be inserted as src

https://i.imgur.com/L1gsd6Ll.jpg

compressed_FRA_9434

**Comment by GMalacaria** [comment]
@peppoasap  ho avuto problemi con il link, ho aggiunto l'immagine negli assets

**Pull request merged**
