### PR TITLE
Add social share component to the workshop pages

### PR DESCRIPTION
**Pull request by peppoasap**
Added social share buttons using the component in repo.
Did some fixes on styles on social share button and checked the changes also on thank-you page to mantain the same layout(just a margin and display change).

Preview:
image

Closes: #80

### CODE REVIEW

**Comment by lucianomurr** [comment]
What if we put the social share button after the title? ( between title and description )

**Comment by peppoasap** [comment]
Just moved it under the description, because I'm using the app-page-header on the page, so would be overcomplicated to put it under the title :)

**Comment by lucianomurr** [comment]
we can close this one when #95 will be closed!

**Comment by lucianomurr** [comment]
we need to update also this one! 👍

**Pull request merged**
