### PR TITLE
feat: Open Graph data

### PR DESCRIPTION
**Pull request by GMalacaria**
changed logic to recover the workshops

​they are recovered via resolver from .md files, each workshop has its own
Added the logic for adding meta for open graph data in the resolver

### CODE REVIEW

**Comment by lucianomurr** [comment]
@GMalacaria what if we prepare the .md files only for the title and meta tag of the workshops?

like this: https://github.com/analogjs/analog/blob/main/apps/blog-app/src/app/pages/blog/resolvers.ts

**Comment by GMalacaria** [comment]
It seems like the only option to me
I'll try to put it into practice
Thanks!

**Comment by lucianomurr** [comment]
@peppoasap could you check if the other MR will be affected by this one?

**Review by lucianomurr — COMMENTED** [review]
probabli we can remove the `api/v1/workshop` files?

**Comment by peppoasap** [comment]
> @peppoasap could you check if the other MR will be affected by this one?

As I can see there will be some conflicts on [slug].page.ts, so probably after the merge of this I can rebase the feature #80.
The api/v1/workshops as I can see is still used by `workshop/index.page.ts`, maybe it could be removed by gathering the workshops .md contents from the new `content` folder to populate the grid?

**Comment by peppoasap** [comment]
> > @peppoasap could you check if the other MR will be affected by this one?
> 
> As I can see there will be some conflicts on [slug].page.ts, so probably after the merge of this I can rebase the feature #80. The api/v1/workshops as I can see is still used by `workshop/index.page.ts`, maybe it could be removed by gathering the workshops .md contents from the new `content` folder to populate the grid?

Let me know if I could take this in charge :)

**Comment by GMalacaria** [comment]
@peppoasap I'm taking care of removing api/v1/workshops
I write when I'm done

**Comment by GMalacaria** [comment]
@peppoasap @lucianomurr i finished the development

**Comment by GMalacaria** [comment]
@peppoasap: development is completed
@lucianomurr: I also wanted to change the meta creation on all the other pages
and fixes on the titles and footer
I hope I did something pleasant

**Pull request merged**
