### PR TITLE
Refactor Header-Menu

### PR DESCRIPTION
**Pull request by GMalacaria**
e.g. https://tailwindui.com/components/marketing/elements/headers

add position fixed

### CODE REVIEW

**Comment by lucianomurr** [comment]
for the best UX experience I think it could be an idea to animate in someway the openings of the menu!

**Comment by GMalacaria** [comment]
@lucianomurr  What do you think?

**Comment by GMalacaria** [comment]
@lucianomurr i removed bold in text header
added past edition popover 
insert header in container

**Review by lucianomurr — APPROVED** [review]
great job!

**Pull request merged**
