### PR TITLE
ng-girl event 2024

### PR DESCRIPTION
**Pull request by GMalacaria**
add file md for event ng-girl 06/2024
fix files md ng-girl 2023 and staying-safe-with-angular

### CODE REVIEW

**Comment by lucianomurr** [comment]
@GMalacaria 
you should add the new path inside the `vite.config`!
Remove also the old `/api` endpoint:
 * '/api/v1/workshops',
 * '/api/v1/workshops/angular-architects-signal-ddd-mfe',

Also, we can split into 2 columns for desktop:
Screenshot 2024-01-16 alle 15 30 34

**Comment by GMalacaria** [comment]
@lucianomurr I finished the development
but I don't like that you have to add the path every time in the prerender. I did some tests to make it dynamic but without success

**Comment by lucianomurr** [comment]
@GMalacaria could we add a longer description, something that we can take from the [nggirls website](https://www.ng-girls.org/event/rome-2024)
Screenshot 2024-01-17 alle 20 37 41

**Comment by GMalacaria** [comment]
@lucianomurr what do you think about it?
"ngGirls created a one-day workshop for women interested in learning to build web applications using the latest technologies, focusing specifically on Angular, an open source platform developed by Google.  The workshop is free and encourages women with basic knowledge in web development to participate.  It is important to increase female representation in the IT sector and we invite mentors, sponsors and anyone interested in supporting the initiative to participate.  The goal is to provide opportunities for women to learn coding skills and become developers, while fostering a supportive community."

**Comment by lucianomurr** [comment]
i've just updated the issue description #101, could you give me a feedback?

**Comment by GMalacaria** [comment]
@lucianomurr added description and new style for button 'expired'

**Pull request merged**
