### PR TITLE
Speaker Page

### PR DESCRIPTION
**Pull request by GMalacaria**
create speaker page, card and modal detail
added 6 speaker:
- Enea Jahollari
- Manfred Steyer
- Natalia Venditto
- Soumaya Erradi
- Alisa Duncan
- Daniela Bonvini

created socialLinkComp and add in team page
created const cfpurl
added speaker in menu

### CODE REVIEW

**Comment by GMalacaria** [comment]
Daniela, Enea gave us an invalid img url, I retrieved one online

**Comment by lucianomurr** [comment]
> @lucianomurr but do we want to put the speakers on the homepage? or do we leave it on a separate page?

In my opinion, if we create some cool UX we can put all toghether in home!

**Comment by lucianomurr** [comment]
in the beginning the page could be without any speakers!
https://www.coderful.io/speakers/

**Comment by GMalacaria** [comment]
@lucianomurr add speakers unknown 
Do we want to change the CFP date?

**Comment by GMalacaria** [comment]
removed cfp references

**Comment by lucianomurr** [comment]
@GMalacaria 
First 3 speakers to publish!

Alisa Duncan
Mateusz Łędzewicz
Enea Jahollari

**Comment by GMalacaria** [comment]
@lucianomurr 
i actived speaker, i added Mateusz Łędzewicz speaker and i changed visible to true for Alisa and Enea

**Pull request merged**
